services:
  frontend:
    image: aimlxv/g26-se-project-fe-68-2:latest
    container_name: dentist-fe
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
      - mongo
    restart: unless-stopped

  backend:
    image: aimlxv/g26-se-project-be-68-2:latest
    container_name: dentist-be
    ports:
      - "5003:5003"
    environment:
      NODE_ENV: production
      PORT: 5003
      TRUST_PROXY: 1
      SWAGGER_BASE_URL: ${SWAGGER_BASE_URL}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      MONGO_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/${DB_NAME}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: 30d
      JWT_COOKIE_EXPIRE: 30
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: dentist-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
