services:
  frontend:
    image: aimlxv/g26-se-project-fe-68-2:latest
    container_name: dentist-fe
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    image: aimlxv/g26-se-project-be-68-2:latest
    container_name: dentist-be
    ports:
      - "5003:5003"
    environment:
      NODE_ENV: production
      PORT: 5003
      TRUST_PROXY: 1
      SWAGGER_BASE_URL: ${SWAGGER_BASE_URL}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: 30d
      JWT_COOKIE_EXPIRE: 30
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
    ports:
      - "127.0.0.1:8080:8080" 
    restart: unless-stopped